# Generated by Django 4.2.4 on 2023-08-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('screen_size', models.FloatField(null=True)),
                ('status', models.BooleanField(choices=[(False, '-'), (True, '+')], null=True)),
                ('builder_country', models.CharField(max_length=100, null=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.brand')),
            ],
        ),
    ]
